config/routes.rb
Rails.application.routes.draw do
resources :recipes

root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  has_many :directions
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true
  validates :title, :description, :image, presence: true
  has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find, only: [:show, :edit, :update, :destroy]

	def index
		@recipes = Recipe.all.order(created_at: :desc)
	end

	def show
		
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
        byebug
        
		if @recipe.save
			redirect_to @recipe, notice: "Successfully created a new recipe"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
		   redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		if @recipe.destroy
		   redirect_to root_path
		end
	end


	private

	def recipe_params
		params.require(:recipe).permit(:title, :description, :image, ingredient_attributes: [:id, :name, :_destroy], directions_attribute: [:id, :step, :_destroy])
	end

	def find
		@recipe = Recipe.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthyFood</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_directions_fields.html.erb
<div class='nested-fields'>
<%= f.input :step %>
<%= link_to_remove_association "Remove", f %>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe do |f| %>
<%= f.input :image %>
<%= f.input :title %>
<%= f.input :description %>
<br><br>

<h2> Ingredients </h2>
<div id='ingredients'>
<%= f.simple_fields_for :ingredients do |ingredient| %>
<%= render 'ingredients_fields', :f => ingredient %>
<% end %>
<div class='links'>
<%= link_to_add_association 'Add Ingredient', f, :ingredients, :partial => 'ingredients_fields' %>
</div></div>
<br><br>

<h2> Directions </h2>
<div id='directions'>
<%= f.simple_fields_for :directions do |direction| %>
<%= render 'directions_fields', :f => direction %>
<% end %>
<div class='links'>
<%= link_to_add_association 'Add Step', f, :directions, :partial => 'directions_fields' %>
</div></div>

<%= f.button :submit %>
<% end %>

app/views/recipes/_ingredients_fields.html.erb
<div class='nested-fields'>
<%= f.input :name %>
<%= link_to_remove_association "Remove", f %>
</div>

app/views/recipes/edit.html.erb
<h1> Edit Recipe </h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<h1> hi </h1>
<% @recipes.each do |recipe| %>
    <%= link_to recipe do %>
    <%= image_tag recipe.image.url(:medium) %>
    <% end %>
	<h2><%= link_to recipe.title, recipe_path(recipe) %></h2>
	<% end %>
<br><br>
<%= link_to "Add Recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1> New Recipe </h1>

<%= render "form" %>

<%= link_to "Home", root_path %>

app/views/recipes/show.html.erb
<h1> <%= @recipe.title %> </h1>
<p><%= image_tag @recipe.image.url(:medium) %></p>
<p> <%= @recipe.description %> </p>
<br>
<div id="ingredients">
<h2>Ingredients</h2>
<ul><%= @recipe.ingredients.each do |ingredient| %>
<li><%= ingredient.name %>
	<% end %>
</li>
</ul>
<br>
<ul>
<div id="directions">
<h2>Directions</h2>
<ul><%= @recipe.directions.each do |direction| %>
<li><%= direction.step %></li>
<% end %>
</ul>
<br>

<%= link_to "Home", root_path %>
<%= link_to "Edit", edit_recipe_path %>
<%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure ?"} %>